/* 
 * Hotelspro Api Client
 *
 * Hotelspro Api Client
 *
 * OpenAPI spec version: 2.0.0
 * Contact: clientintegration@hotelspro.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package hotelspro_client

type AvailabilityResponse struct {

	MealType string `json:"meal_type"`

	DestinationCode string `json:"destination_code"`

	Nonrefundable bool `json:"nonrefundable,omitempty"`

	Offer bool `json:"offer"`

	Checkout string `json:"checkout"`

	Price string `json:"price"`

	SupportsCancellation bool `json:"supports_cancellation"`

	HotelCode string `json:"hotel_code"`

	Currency string `json:"currency"`

	HotelCurrency string `json:"hotel_currency,omitempty"`

	HotelPrice string `json:"hotel_price,omitempty"`

	Checkin string `json:"checkin"`

	Rooms []Room `json:"rooms"`

	Policies []Policy `json:"policies"`

	View bool `json:"view,omitempty"`

	MinimumSellingPrice string `json:"minimum_selling_price,omitempty"`

	AdditionalInfo string `json:"additional_info,omitempty"`

	PayAtHotel bool `json:"pay_at_hotel"`
}
