/* 
 * Hotelspro Api Client
 *
 * Hotelspro Api Client
 *
 * OpenAPI spec version: 2.0.0
 * Contact: clientintegration@hotelspro.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package hotelspro_client

type BookResponseHotelPaymentInfo struct {

	HotelCurrency string `json:"hotel_currency,omitempty"`

	HotelPrice string `json:"hotel_price,omitempty"`
}
