/* 
 * Hotelspro Api Client
 *
 * Hotelspro Api Client
 *
 * OpenAPI spec version: 2.0.0
 * Contact: clientintegration@hotelspro.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package hotelspro_client

type BookResponseRooms struct {

	RoomDescription string `json:"room_description,omitempty"`

	RoomType string `json:"room_type,omitempty"`
}
