/* 
 * Hotelspro Api Client
 *
 * Hotelspro Api Client
 *
 * OpenAPI spec version: 2.0.0
 * Contact: clientintegration@hotelspro.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package hotelspro_client

type CancelResponse struct {

	Currency string `json:"currency"`

	ChargeAmount string `json:"charge_amount"`

	Code string `json:"code"`
}
