/* 
 * Hotelspro Api Client
 *
 * Hotelspro Api Client
 *
 * OpenAPI spec version: 2.0.0
 * Contact: clientintegration@hotelspro.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package hotelspro_client

type HotelAvailabilityResponse struct {

	// number of returned hotel
	Count int32 `json:"count"`

	// search code
	Code string `json:"code"`

	Results []Product `json:"results"`
}
