/* 
 * Hotelspro Api Client
 *
 * Hotelspro Api Client
 *
 * OpenAPI spec version: 2.0.0
 * Contact: clientintegration@hotelspro.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package hotelspro_client

type Pax struct {

	AdultQuantity int32 `json:"adult_quantity,omitempty"`

	ChildrenAges []int32 `json:"children_ages,omitempty"`
}
