/* 
 * Hotelspro Api Client
 *
 * Hotelspro Api Client
 *
 * OpenAPI spec version: 2.0.0
 * Contact: clientintegration@hotelspro.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package hotelspro_client

type Policy struct {

	Ratio string `json:"ratio,omitempty"`

	DaysRemaining int32 `json:"days_remaining,omitempty"`
}
