/* 
 * Hotelspro Api Client
 *
 * Hotelspro Api Client
 *
 * OpenAPI spec version: 2.0.0
 * Contact: clientintegration@hotelspro.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package hotelspro_client

type Room struct {

	Pax *Pax `json:"pax,omitempty"`

	RoomCategory string `json:"room_category,omitempty"`

	RoomDescription string `json:"room_description,omitempty"`

	NightlyPrices *interface{} `json:"nightly_prices,omitempty"`

	RoomType string `json:"room_type,omitempty"`
}
