/* 
 * Hotelspro Api Client
 *
 * Hotelspro Api Client
 *
 * OpenAPI spec version: 2.0.0
 * Contact: clientintegration@hotelspro.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package hotelspro_client

type SearchResponse struct {

	// number of returned hotel
	Count int32 `json:"count"`

	// search code
	Code string `json:"code"`

	// next page code
	NextPageCode string `json:"next_page_code,omitempty"`

	MaxWait string `json:"max_wait"`

	ResponseTime string `json:"response_time"`

	Results []Results `json:"results"`
}
